DATA:
    ROOT: '/home/c3-0/datasets/somethingsomething/videos'
    TRAIN_FILE: ''
    VAL_FILE: ''
    DATASET: ssv2
    NUM_FRAMES: 32
    NUM_CLASSES: 26
    LABEL_LIST: 'labels/ssv2_head_labels.csv'
MODEL:
    ARCH: ViT-B/16
TRAIN:
    BATCH_SIZE: 4 #8 for 48gb; BS 64; here batch size means images that can be held in memory of 1 gpu, more gpus can run more processes of same batch size
    ACCUMULATION_STEPS: 2
    EPOCHS: 50 #50
    LR: 2.e-06
