DATA:
    ROOT: '/home/c3-0/datasets/somethingsomething/videos'
    TRAIN_FILE: 'datasets_splits/ssv2_custom_splits/ssv2_distribution3_base2novel/ssv2_tr_act_set1.txt'
    VAL_FILE: 'datasets_splits/ssv2_custom_splits/ssv2_distribution3_base2novel/ssv2_val_act_set2.txt'
    DATASET: ssv2
    NUM_FRAMES: 32
    NUM_CLASSES: 68
    LABEL_LIST: 'labels/ssv2_149_set2_labels_distribution3.csv'
MODEL:
    ARCH: ViT-B/16
TRAIN:
    BATCH_SIZE: 4 # BS 64
    ACCUMULATION_STEPS: 2
    EPOCHS: 50 #11
    LR: 2.e-06
TRAINER:
  ViFi_CLIP:
    ZS_EVAL: False # Make True only during test mode to evaluate zero-shot vanilla CLIP performance
    USE: "both" # both refers to complete fine-tuning of CLIP (text+image encoders)
SAVE_FREQ: 5