TRAIN:
  ENABLE: true
  DATASET: kinetics
  BATCH_SIZE: 12
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 2
  AUTO_RESUME: true
DATA:
  USE_OFFSET_SAMPLING: true
  DECODING_BACKEND: pyav
  NUM_FRAMES: 16
  SAMPLING_RATE: 4
  TRAIN_JITTER_SCALES:
  - 256
  - 320
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM:
  - 3
  PATH_TO_DATA_DIR: /data/k8s/work_dirs/e33252/analysis/kinetics400/slowfast/datasets/k400/k400_head_classes_v2/tr_set1_val_set1
  TRAIN_JITTER_SCALES_RELATIVE:
  - 0.08
  - 1.0
  TRAIN_JITTER_ASPECT_RELATIVE:
  - 0.75
  - 1.3333
MVIT:
  ZERO_DECAY_POS_CLS: false
  USE_ABS_POS: false
  REL_POS_SPATIAL: true
  REL_POS_TEMPORAL: true
  DEPTH: 16
  NUM_HEADS: 1
  EMBED_DIM: 96
  PATCH_KERNEL: (3, 7, 7)
  PATCH_STRIDE: (2, 4, 4)
  PATCH_PADDING: (1, 3, 3)
  MLP_RATIO: 4.0
  QKV_BIAS: true
  DROPPATH_RATE: 0.2
  NORM: layernorm
  MODE: conv
  CLS_EMBED_ON: true
  DIM_MUL:
  - - 1
    - 2.0
  - - 3
    - 2.0
  - - 14
    - 2.0
  HEAD_MUL:
  - - 1
    - 2.0
  - - 3
    - 2.0
  - - 14
    - 2.0
  POOL_KVQ_KERNEL:
  - 3
  - 3
  - 3
  POOL_KV_STRIDE_ADAPTIVE:
  - 1
  - 8
  - 8
  POOL_Q_STRIDE:
  - - 0
    - 1
    - 1
    - 1
  - - 1
    - 1
    - 2
    - 2
  - - 2
    - 1
    - 1
    - 1
  - - 3
    - 1
    - 2
    - 2
  - - 4
    - 1
    - 1
    - 1
  - - 5
    - 1
    - 1
    - 1
  - - 6
    - 1
    - 1
    - 1
  - - 7
    - 1
    - 1
    - 1
  - - 8
    - 1
    - 1
    - 1
  - - 9
    - 1
    - 1
    - 1
  - - 10
    - 1
    - 1
    - 1
  - - 11
    - 1
    - 1
    - 1
  - - 12
    - 1
    - 1
    - 1
  - - 13
    - 1
    - 1
    - 1
  - - 14
    - 1
    - 2
    - 2
  - - 15
    - 1
    - 1
    - 1
  DROPOUT_RATE: 0.0
  DIM_MUL_IN_ATT: true
  RESIDUAL_POOLING: true
AUG:
  NUM_SAMPLE: 2
  ENABLE: true
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  INTERPOLATION: bicubic
  RE_PROB: 0.25
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: false
MIXUP:
  ENABLE: true
  ALPHA: 0.8
  CUTMIX_ALPHA: 1.0
  PROB: 1.0
  SWITCH_PROB: 0.5
  LABEL_SMOOTH_VALUE: 0.1
SOLVER:
  ZERO_WD_1D_PARAM: true
  BASE_LR_SCALE_NUM_SHARDS: true
  CLIP_GRAD_L2NORM: 1.0
  BASE_LR: 0.0001
  COSINE_AFTER_WARMUP: true
  COSINE_END_LR: 1.0e-06
  WARMUP_START_LR: 1.0e-06
  WARMUP_EPOCHS: 5.0
  LR_POLICY: cosine
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05
  OPTIMIZING_METHOD: adamw
MODEL:
  NUM_CLASSES: 41
  ARCH: mvit
  MODEL_NAME: MViT
  LOSS_FUNC: soft_cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: false
  DATASET: kinetics
  BATCH_SIZE: 8
  NUM_SPATIAL_CROPS: 1
  NUM_ENSEMBLE_VIEWS: 5
DATA_LOADER:
  NUM_WORKERS: 16
  PIN_MEMORY: true
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: output/v2/k400_head_classes_v2/mvit/mvit_tr_set1_val_set1
