DATA:
    ROOT: '/home/c3-0/datasets/kinetics400_dataset'
    TRAIN_FILE: ''
    VAL_FILE: ''
    DATASET: kinetics400
    NUM_FRAMES: 16
    NUM_CLASSES: 41
    LABEL_LIST: 'labels/kinetics_400_head_labels.csv'
MODEL:
    ARCH: ViT-B/16
TRAIN:
    BATCH_SIZE: 20 # 4 #BS 512
    ACCUMULATION_STEPS: 2 #16
    EPOCHS: 50
    LR: 2.2e-05
    AUTO_RESUME: True
TRAINER:
  ViFi_CLIP:
    ZS_EVAL: False # Make True only during test mode to evaluate zero-shot vanilla CLIP performance
    USE: "both" # both refers to complete fine-tuning of CLIP (text+image encoders)
SAVE_FREQ: 5