DATA:
    ROOT: '/home/c3-0/datasets/somethingsomething/videos'
    TRAIN_FILE: ''
    VAL_FILE: ''
    DATASET: ssv2
    NUM_FRAMES: 32
    NUM_CLASSES: 26
    LABEL_LIST: 'labels/ssv2_head_labels.csv'
MODEL:
    ARCH: ViT-B/16
TRAIN:
    AUTO_RESUME: True
    BATCH_SIZE: 4 # BS 64
    ACCUMULATION_STEPS: 2
    EPOCHS: 50
    LR: 2.e-06
TRAINER:
  ViFi_CLIP:
    ZS_EVAL: False # Make True only during test mode to evaluate zero-shot vanilla CLIP performance
    USE: "both" # both refers to complete fine-tuning of CLIP (text+image encoders)
SAVE_FREQ: 5