TRAIN:
  DATASET: kinetics
  BATCH_SIZE: 64
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 2
  AUTO_RESUME: true
  ENABLE: true
X3D:
  WIDTH_FACTOR: 2.0
  DEPTH_FACTOR: 2.2
  BOTTLENECK_FACTOR: 2.25
  DIM_C5: 2048
  DIM_C1: 12
TEST:
  ENABLE: false
  DATASET: kinetics
  BATCH_SIZE: 48
  NUM_SPATIAL_CROPS: 3
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 5
  TRAIN_JITTER_SCALES:
  - 256
  - 320
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM:
  - 3
  DECODING_BACKEND: pyav
  PATH_TO_DATA_DIR: /data/k8s/work_dirs/e33252/analysis/kinetics400/slowfast/datasets/k400/k400_head_classes_v2/tr_set1_val_set1
RESNET:
  ZERO_INIT_FINAL_BN: true
  TRANS_FUNC: x3d_transform
  STRIDE_1X1: false
BN:
  USE_PRECISE_STATS: true
  NUM_BATCHES_PRECISE: 200
  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 0.1
  BASE_LR_SCALE_NUM_SHARDS: true
  LR_POLICY: cosine
  MAX_EPOCH: 50
  WEIGHT_DECAY: 5.0e-05
  WARMUP_EPOCHS: 5.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 41
  ARCH: x3d
  MODEL_NAME: X3D
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: true
NUM_GPUS: 4
RNG_SEED: 0
OUTPUT_DIR: output/v2/k400_head_classes_v2/x3d/x3d_tr_set1_val_set1
NUM_SHARDS: 1
