#custom made by Raiyaan
TRAIN:
  ENABLE: True
  DATASET: ssv2 #ptvssv2 
  BATCH_SIZE: 64
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 2
  AUTO_RESUME: True
  # CHECKPOINT_FILE_PATH: # please download from the model zoo.
  CHECKPOINT_EPOCH_RESET: True
X3D:
  WIDTH_FACTOR: 2.0
  DEPTH_FACTOR: 2.2
  BOTTLENECK_FACTOR: 2.25
  DIM_C5: 2048
  DIM_C1: 12
TEST:
  ENABLE: True
  DATASET: ssv2 #ptvssv2
  BATCH_SIZE: 64
  NUM_SPATIAL_CROPS: 3
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 5
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  # TEST_CROP_SIZE: 224 # use if TEST.NUM_SPATIAL_CROPS: 1
  TEST_CROP_SIZE: 256 # use if TEST.NUM_SPATIAL_CROPS: 3
  INPUT_CHANNEL_NUM: [3]
  INV_UNIFORM_SAMPLE: True
  RANDOM_FLIP: False
  REVERSE_INPUT_CHANNEL: True
  PATH_TO_DATA_DIR: /home/ra164195/slowfast/datasets/ssv2/tr_set1_val_set1
  PATH_PREFIX: /home/ra164195/Datasets/SSv2/extracted_frames
RESNET:
  ZERO_INIT_FINAL_BN: True
  TRANS_FUNC: x3d_transform
  STRIDE_1X1: False
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 150
  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 0.1 # 1 machine
  BASE_LR_SCALE_NUM_SHARDS: True
  LR_POLICY: cosine
  MAX_EPOCH: 100
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 10.0
  WARMUP_START_LR: 0.08
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 26 #174
  ARCH: x3d
  MODEL_NAME: PTVX3D
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True
NUM_GPUS: 2 #2 for train, 1 for eval
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: output/distribution3_head_classes/x3d_ssv2_tr_set1_val_set1

