DATA:
    ROOT: 'path_to_dataset'
    TRAIN_FILE: 'path_to_train_videos_list'
    VAL_FILE: 'path_to_val_videos_list'
    DATASET: kinetics400
    NUM_FRAMES: 16
    NUM_CLASSES: 41
    LABEL_LIST: 'path_to_label_list'
MODEL:
    ARCH: ViT-B/16
TRAIN:
    BATCH_SIZE: 20 
    ACCUMULATION_STEPS: 2 
    EPOCHS: 50
    LR: 2.2e-05
    AUTO_RESUME: True
TRAINER:
  ViFi_CLIP:
    ZS_EVAL: False # Make True only during test mode to evaluate zero-shot vanilla CLIP performance
    USE: "both" # both refers to complete fine-tuning of CLIP (text+image encoders)
SAVE_FREQ: 5