resume:   # '/cluster/datastore/shahzaa/Code/Prompt_Adaptor_mix_work/Exp_new/clip_k400/ViT-B/32/kinetics400/base_to_novel_something_something/last_model.pt'
pretrain:
weight_save_dir: 'Exp'
seed: 1024
use_motion_loss: True
training_name: 'tr_set1_val_set2_head_ssv2_ablation1'
prompt:
    use: True
    # num_of_token: 100 #197
    # num_of_text_token: 50   #77
    INITIATION: 'random' 
    DEEP: True
    DROPOUT: 0.1
data:
    dataset: ssv2
    modality: RGB
    num_segments: 8 # nunber of frames per video 
    seg_length: 1
    batch_size: 40 #50
    workers: 4
    image_tmpl: 'img_{:05d}.jpg'
    use_llm: True
    ###################################### SSv2 base ############################
    train_list: 'dataset_splits/SSv2_custom/ssv2_distribution3_head_classes/SS_train_set1.txt'
    val_list: 'dataset_splits/SSv2_custom/ssv2_distribution3_head_classes/SS_val_set1.txt' #
    gpt_discription: 'GPT_discription/Something_gpt_Class_discription_new_head.csv'
    label_list: 'dataset_splits/SSv2_custom/ssv2_distribution3_head_classes/SS_head_labels.csv'
    ############## SSv2 novel ################
    novel_val_list: 'dataset_splits/SSv2_custom/ssv2_distribution3_head_classes/SS_val_set2.txt' #
    novel_gpt_discription: 'GPT_discription/Something_gpt_Class_discription_new_head.csv'
    novel_label_list: 'dataset_splits/SSv2_custom/ssv2_distribution3_head_classes/SS_head_labels.csv'
    #############
    index_bias: 1
    input_size: 224
    randaug:
        N: 0 #2
        M: 0  #9
    random_shift: False #True
network:
    arch: ViT-B/16  #ViT-B/32 ViT-B/16 ViT-L/14
    init: True
    tsm: False
    drop_out: 0.1
    emb_dropout: 0.0
    type: clip_ssv2
    sim_header: "Transf"  #Transf   meanP  LSTM Conv_1D Transf_cls
    joint: False
    describe:
solver:
    type: cosine
    epochs: 71 #100
    start_epoch: 0
    epoch_offset: 0
    optim: adamw
    lr: 1.e-4 #1.e-5 #5.e-6
    lr_warmup_step: 5
    momentum: 0.9
    weight_decay: 0.2
    lr_decay_step: 15
    lr_decay_factor: 0.1
    clip_gradient: 20
    loss_type: nll
    evaluate: False
    ratio: 1
    f_ratio: 10
logging:
    print_freq: 10
    eval_freq: 5 #1