DATA:
    ROOT: '/home/c3-0/datasets/kinetics400_dataset'
    TRAIN_FILE: 'datasets_splits/k400_custom_splits/k400_base2novel/train_set1.txt'
    VAL_FILE: 'datasets_splits/k400_custom_splits/k400_base2novel/val_set1.txt'
    DATASET: kinetics400
    NUM_FRAMES: 32
    NUM_CLASSES: 111
    LABEL_LIST: 'labels/kinetics_400_205_set1_labels.csv'
MODEL:
    ARCH: ViT-B/16
TRAIN:
    BATCH_SIZE: 5 #8 #4
    ACCUMULATION_STEPS: 2 #8
    EPOCHS: 50 #50
SAVE_FREQ: 1