DATA:
    ROOT: '/home/c3-0/datasets/somethingsomething/videos'
    TRAIN_FILE: 'datasets_splits/ssv2_custom_splits/ssv2_distribution3_base2novel/ssv2_tr_act_set1.txt'
    VAL_FILE: 'datasets_splits/ssv2_custom_splits/ssv2_distribution3_base2novel/ssv2_val_act_set1.txt'
    DATASET: ssv2
    NUM_FRAMES: 32
    NUM_CLASSES: 81
    LABEL_LIST: 'labels/ssv2_149_set1_labels_distribution3.csv'
MODEL:
    ARCH: ViT-B/16
TRAIN:
    BATCH_SIZE: 8 # BS 64
    ACCUMULATION_STEPS: 2
    EPOCHS: 50 
    LR: 2.e-06
SAVE_FREQ: 5